###############################################################
#  Generated by:      Cadence Innovus 15.20-p005_1
#  OS:                Linux x86_64(Host ID ufrgs-server-09)
#  Generated on:      Tue Nov 20 16:02:44 2018
#  Design:            z80_topzera
#  Command:           create_floorplan -site core -core_density_size 1 0.75 10.0 10.0 10.0 10.0
###############################################################

Version: 8

Head Box: 0.0000 0.0000 1174.0000 1962.0000
IO Box: 257.0000 257.0000 917.0000 1705.0000
Core Box: 257.0400 257.4200 917.0000 1701.9000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 257.0400 257.4200 FS 1047 1 0.6300 0.0000
DefRow: ROW_1 core 257.0400 262.3000 N 1047 1 0.6300 0.0000
DefRow: ROW_2 core 257.0400 267.1800 FS 1047 1 0.6300 0.0000
DefRow: ROW_3 core 257.0400 272.0600 N 1047 1 0.6300 0.0000
DefRow: ROW_4 core 257.0400 276.9400 FS 1047 1 0.6300 0.0000
DefRow: ROW_5 core 257.0400 281.8200 N 1047 1 0.6300 0.0000
DefRow: ROW_6 core 257.0400 286.7000 FS 1047 1 0.6300 0.0000
DefRow: ROW_7 core 257.0400 291.5800 N 1047 1 0.6300 0.0000
DefRow: ROW_8 core 257.0400 296.4600 FS 1047 1 0.6300 0.0000
DefRow: ROW_9 core 257.0400 301.3400 N 1047 1 0.6300 0.0000
DefRow: ROW_10 core 257.0400 306.2200 FS 1047 1 0.6300 0.0000
DefRow: ROW_11 core 257.0400 311.1000 N 1047 1 0.6300 0.0000
DefRow: ROW_12 core 257.0400 315.9800 FS 1047 1 0.6300 0.0000
DefRow: ROW_13 core 257.0400 320.8600 N 1047 1 0.6300 0.0000
DefRow: ROW_14 core 257.0400 325.7400 FS 1047 1 0.6300 0.0000
DefRow: ROW_15 core 257.0400 330.6200 N 1047 1 0.6300 0.0000
DefRow: ROW_16 core 257.0400 335.5000 FS 1047 1 0.6300 0.0000
DefRow: ROW_17 core 257.0400 340.3800 N 1047 1 0.6300 0.0000
DefRow: ROW_18 core 257.0400 345.2600 FS 1047 1 0.6300 0.0000
DefRow: ROW_19 core 257.0400 350.1400 N 1047 1 0.6300 0.0000
DefRow: ROW_20 core 257.0400 355.0200 FS 1047 1 0.6300 0.0000
DefRow: ROW_21 core 257.0400 359.9000 N 1047 1 0.6300 0.0000
DefRow: ROW_22 core 257.0400 364.7800 FS 1047 1 0.6300 0.0000
DefRow: ROW_23 core 257.0400 369.6600 N 1047 1 0.6300 0.0000
DefRow: ROW_24 core 257.0400 374.5400 FS 1047 1 0.6300 0.0000
DefRow: ROW_25 core 257.0400 379.4200 N 1047 1 0.6300 0.0000
DefRow: ROW_26 core 257.0400 384.3000 FS 1047 1 0.6300 0.0000
DefRow: ROW_27 core 257.0400 389.1800 N 1047 1 0.6300 0.0000
DefRow: ROW_28 core 257.0400 394.0600 FS 1047 1 0.6300 0.0000
DefRow: ROW_29 core 257.0400 398.9400 N 1047 1 0.6300 0.0000
DefRow: ROW_30 core 257.0400 403.8200 FS 1047 1 0.6300 0.0000
DefRow: ROW_31 core 257.0400 408.7000 N 1047 1 0.6300 0.0000
DefRow: ROW_32 core 257.0400 413.5800 FS 1047 1 0.6300 0.0000
DefRow: ROW_33 core 257.0400 418.4600 N 1047 1 0.6300 0.0000
DefRow: ROW_34 core 257.0400 423.3400 FS 1047 1 0.6300 0.0000
DefRow: ROW_35 core 257.0400 428.2200 N 1047 1 0.6300 0.0000
DefRow: ROW_36 core 257.0400 433.1000 FS 1047 1 0.6300 0.0000
DefRow: ROW_37 core 257.0400 437.9800 N 1047 1 0.6300 0.0000
DefRow: ROW_38 core 257.0400 442.8600 FS 1047 1 0.6300 0.0000
DefRow: ROW_39 core 257.0400 447.7400 N 1047 1 0.6300 0.0000
DefRow: ROW_40 core 257.0400 452.6200 FS 1047 1 0.6300 0.0000
DefRow: ROW_41 core 257.0400 457.5000 N 1047 1 0.6300 0.0000
DefRow: ROW_42 core 257.0400 462.3800 FS 1047 1 0.6300 0.0000
DefRow: ROW_43 core 257.0400 467.2600 N 1047 1 0.6300 0.0000
DefRow: ROW_44 core 257.0400 472.1400 FS 1047 1 0.6300 0.0000
DefRow: ROW_45 core 257.0400 477.0200 N 1047 1 0.6300 0.0000
DefRow: ROW_46 core 257.0400 481.9000 FS 1047 1 0.6300 0.0000
DefRow: ROW_47 core 257.0400 486.7800 N 1047 1 0.6300 0.0000
DefRow: ROW_48 core 257.0400 491.6600 FS 1047 1 0.6300 0.0000
DefRow: ROW_49 core 257.0400 496.5400 N 1047 1 0.6300 0.0000
DefRow: ROW_50 core 257.0400 501.4200 FS 1047 1 0.6300 0.0000
DefRow: ROW_51 core 257.0400 506.3000 N 1047 1 0.6300 0.0000
DefRow: ROW_52 core 257.0400 511.1800 FS 1047 1 0.6300 0.0000
DefRow: ROW_53 core 257.0400 516.0600 N 1047 1 0.6300 0.0000
DefRow: ROW_54 core 257.0400 520.9400 FS 1047 1 0.6300 0.0000
DefRow: ROW_55 core 257.0400 525.8200 N 1047 1 0.6300 0.0000
DefRow: ROW_56 core 257.0400 530.7000 FS 1047 1 0.6300 0.0000
DefRow: ROW_57 core 257.0400 535.5800 N 1047 1 0.6300 0.0000
DefRow: ROW_58 core 257.0400 540.4600 FS 1047 1 0.6300 0.0000
DefRow: ROW_59 core 257.0400 545.3400 N 1047 1 0.6300 0.0000
DefRow: ROW_60 core 257.0400 550.2200 FS 1047 1 0.6300 0.0000
DefRow: ROW_61 core 257.0400 555.1000 N 1047 1 0.6300 0.0000
DefRow: ROW_62 core 257.0400 559.9800 FS 1047 1 0.6300 0.0000
DefRow: ROW_63 core 257.0400 564.8600 N 1047 1 0.6300 0.0000
DefRow: ROW_64 core 257.0400 569.7400 FS 1047 1 0.6300 0.0000
DefRow: ROW_65 core 257.0400 574.6200 N 1047 1 0.6300 0.0000
DefRow: ROW_66 core 257.0400 579.5000 FS 1047 1 0.6300 0.0000
DefRow: ROW_67 core 257.0400 584.3800 N 1047 1 0.6300 0.0000
DefRow: ROW_68 core 257.0400 589.2600 FS 1047 1 0.6300 0.0000
DefRow: ROW_69 core 257.0400 594.1400 N 1047 1 0.6300 0.0000
DefRow: ROW_70 core 257.0400 599.0200 FS 1047 1 0.6300 0.0000
DefRow: ROW_71 core 257.0400 603.9000 N 1047 1 0.6300 0.0000
DefRow: ROW_72 core 257.0400 608.7800 FS 1047 1 0.6300 0.0000
DefRow: ROW_73 core 257.0400 613.6600 N 1047 1 0.6300 0.0000
DefRow: ROW_74 core 257.0400 618.5400 FS 1047 1 0.6300 0.0000
DefRow: ROW_75 core 257.0400 623.4200 N 1047 1 0.6300 0.0000
DefRow: ROW_76 core 257.0400 628.3000 FS 1047 1 0.6300 0.0000
DefRow: ROW_77 core 257.0400 633.1800 N 1047 1 0.6300 0.0000
DefRow: ROW_78 core 257.0400 638.0600 FS 1047 1 0.6300 0.0000
DefRow: ROW_79 core 257.0400 642.9400 N 1047 1 0.6300 0.0000
DefRow: ROW_80 core 257.0400 647.8200 FS 1047 1 0.6300 0.0000
DefRow: ROW_81 core 257.0400 652.7000 N 1047 1 0.6300 0.0000
DefRow: ROW_82 core 257.0400 657.5800 FS 1047 1 0.6300 0.0000
DefRow: ROW_83 core 257.0400 662.4600 N 1047 1 0.6300 0.0000
DefRow: ROW_84 core 257.0400 667.3400 FS 1047 1 0.6300 0.0000
DefRow: ROW_85 core 257.0400 672.2200 N 1047 1 0.6300 0.0000
DefRow: ROW_86 core 257.0400 677.1000 FS 1047 1 0.6300 0.0000
DefRow: ROW_87 core 257.0400 681.9800 N 1047 1 0.6300 0.0000
DefRow: ROW_88 core 257.0400 686.8600 FS 1047 1 0.6300 0.0000
DefRow: ROW_89 core 257.0400 691.7400 N 1047 1 0.6300 0.0000
DefRow: ROW_90 core 257.0400 696.6200 FS 1047 1 0.6300 0.0000
DefRow: ROW_91 core 257.0400 701.5000 N 1047 1 0.6300 0.0000
DefRow: ROW_92 core 257.0400 706.3800 FS 1047 1 0.6300 0.0000
DefRow: ROW_93 core 257.0400 711.2600 N 1047 1 0.6300 0.0000
DefRow: ROW_94 core 257.0400 716.1400 FS 1047 1 0.6300 0.0000
DefRow: ROW_95 core 257.0400 721.0200 N 1047 1 0.6300 0.0000
DefRow: ROW_96 core 257.0400 725.9000 FS 1047 1 0.6300 0.0000
DefRow: ROW_97 core 257.0400 730.7800 N 1047 1 0.6300 0.0000
DefRow: ROW_98 core 257.0400 735.6600 FS 1047 1 0.6300 0.0000
DefRow: ROW_99 core 257.0400 740.5400 N 1047 1 0.6300 0.0000
DefRow: ROW_100 core 257.0400 745.4200 FS 1047 1 0.6300 0.0000
DefRow: ROW_101 core 257.0400 750.3000 N 1047 1 0.6300 0.0000
DefRow: ROW_102 core 257.0400 755.1800 FS 1047 1 0.6300 0.0000
DefRow: ROW_103 core 257.0400 760.0600 N 1047 1 0.6300 0.0000
DefRow: ROW_104 core 257.0400 764.9400 FS 1047 1 0.6300 0.0000
DefRow: ROW_105 core 257.0400 769.8200 N 1047 1 0.6300 0.0000
DefRow: ROW_106 core 257.0400 774.7000 FS 1047 1 0.6300 0.0000
DefRow: ROW_107 core 257.0400 779.5800 N 1047 1 0.6300 0.0000
DefRow: ROW_108 core 257.0400 784.4600 FS 1047 1 0.6300 0.0000
DefRow: ROW_109 core 257.0400 789.3400 N 1047 1 0.6300 0.0000
DefRow: ROW_110 core 257.0400 794.2200 FS 1047 1 0.6300 0.0000
DefRow: ROW_111 core 257.0400 799.1000 N 1047 1 0.6300 0.0000
DefRow: ROW_112 core 257.0400 803.9800 FS 1047 1 0.6300 0.0000
DefRow: ROW_113 core 257.0400 808.8600 N 1047 1 0.6300 0.0000
DefRow: ROW_114 core 257.0400 813.7400 FS 1047 1 0.6300 0.0000
DefRow: ROW_115 core 257.0400 818.6200 N 1047 1 0.6300 0.0000
DefRow: ROW_116 core 257.0400 823.5000 FS 1047 1 0.6300 0.0000
DefRow: ROW_117 core 257.0400 828.3800 N 1047 1 0.6300 0.0000
DefRow: ROW_118 core 257.0400 833.2600 FS 1047 1 0.6300 0.0000
DefRow: ROW_119 core 257.0400 838.1400 N 1047 1 0.6300 0.0000
DefRow: ROW_120 core 257.0400 843.0200 FS 1047 1 0.6300 0.0000
DefRow: ROW_121 core 257.0400 847.9000 N 1047 1 0.6300 0.0000
DefRow: ROW_122 core 257.0400 852.7800 FS 1047 1 0.6300 0.0000
DefRow: ROW_123 core 257.0400 857.6600 N 1047 1 0.6300 0.0000
DefRow: ROW_124 core 257.0400 862.5400 FS 1047 1 0.6300 0.0000
DefRow: ROW_125 core 257.0400 867.4200 N 1047 1 0.6300 0.0000
DefRow: ROW_126 core 257.0400 872.3000 FS 1047 1 0.6300 0.0000
DefRow: ROW_127 core 257.0400 877.1800 N 1047 1 0.6300 0.0000
DefRow: ROW_128 core 257.0400 882.0600 FS 1047 1 0.6300 0.0000
DefRow: ROW_129 core 257.0400 886.9400 N 1047 1 0.6300 0.0000
DefRow: ROW_130 core 257.0400 891.8200 FS 1047 1 0.6300 0.0000
DefRow: ROW_131 core 257.0400 896.7000 N 1047 1 0.6300 0.0000
DefRow: ROW_132 core 257.0400 901.5800 FS 1047 1 0.6300 0.0000
DefRow: ROW_133 core 257.0400 906.4600 N 1047 1 0.6300 0.0000
DefRow: ROW_134 core 257.0400 911.3400 FS 1047 1 0.6300 0.0000
DefRow: ROW_135 core 257.0400 916.2200 N 1047 1 0.6300 0.0000
DefRow: ROW_136 core 257.0400 921.1000 FS 1047 1 0.6300 0.0000
DefRow: ROW_137 core 257.0400 925.9800 N 1047 1 0.6300 0.0000
DefRow: ROW_138 core 257.0400 930.8600 FS 1047 1 0.6300 0.0000
DefRow: ROW_139 core 257.0400 935.7400 N 1047 1 0.6300 0.0000
DefRow: ROW_140 core 257.0400 940.6200 FS 1047 1 0.6300 0.0000
DefRow: ROW_141 core 257.0400 945.5000 N 1047 1 0.6300 0.0000
DefRow: ROW_142 core 257.0400 950.3800 FS 1047 1 0.6300 0.0000
DefRow: ROW_143 core 257.0400 955.2600 N 1047 1 0.6300 0.0000
DefRow: ROW_144 core 257.0400 960.1400 FS 1047 1 0.6300 0.0000
DefRow: ROW_145 core 257.0400 965.0200 N 1047 1 0.6300 0.0000
DefRow: ROW_146 core 257.0400 969.9000 FS 1047 1 0.6300 0.0000
DefRow: ROW_147 core 257.0400 974.7800 N 1047 1 0.6300 0.0000
DefRow: ROW_148 core 257.0400 979.6600 FS 1047 1 0.6300 0.0000
DefRow: ROW_149 core 257.0400 984.5400 N 1047 1 0.6300 0.0000
DefRow: ROW_150 core 257.0400 989.4200 FS 1047 1 0.6300 0.0000
DefRow: ROW_151 core 257.0400 994.3000 N 1047 1 0.6300 0.0000
DefRow: ROW_152 core 257.0400 999.1800 FS 1047 1 0.6300 0.0000
DefRow: ROW_153 core 257.0400 1004.0600 N 1047 1 0.6300 0.0000
DefRow: ROW_154 core 257.0400 1008.9400 FS 1047 1 0.6300 0.0000
DefRow: ROW_155 core 257.0400 1013.8200 N 1047 1 0.6300 0.0000
DefRow: ROW_156 core 257.0400 1018.7000 FS 1047 1 0.6300 0.0000
DefRow: ROW_157 core 257.0400 1023.5800 N 1047 1 0.6300 0.0000
DefRow: ROW_158 core 257.0400 1028.4600 FS 1047 1 0.6300 0.0000
DefRow: ROW_159 core 257.0400 1033.3400 N 1047 1 0.6300 0.0000
DefRow: ROW_160 core 257.0400 1038.2200 FS 1047 1 0.6300 0.0000
DefRow: ROW_161 core 257.0400 1043.1000 N 1047 1 0.6300 0.0000
DefRow: ROW_162 core 257.0400 1047.9800 FS 1047 1 0.6300 0.0000
DefRow: ROW_163 core 257.0400 1052.8600 N 1047 1 0.6300 0.0000
DefRow: ROW_164 core 257.0400 1057.7400 FS 1047 1 0.6300 0.0000
DefRow: ROW_165 core 257.0400 1062.6200 N 1047 1 0.6300 0.0000
DefRow: ROW_166 core 257.0400 1067.5000 FS 1047 1 0.6300 0.0000
DefRow: ROW_167 core 257.0400 1072.3800 N 1047 1 0.6300 0.0000
DefRow: ROW_168 core 257.0400 1077.2600 FS 1047 1 0.6300 0.0000
DefRow: ROW_169 core 257.0400 1082.1400 N 1047 1 0.6300 0.0000
DefRow: ROW_170 core 257.0400 1087.0200 FS 1047 1 0.6300 0.0000
DefRow: ROW_171 core 257.0400 1091.9000 N 1047 1 0.6300 0.0000
DefRow: ROW_172 core 257.0400 1096.7800 FS 1047 1 0.6300 0.0000
DefRow: ROW_173 core 257.0400 1101.6600 N 1047 1 0.6300 0.0000
DefRow: ROW_174 core 257.0400 1106.5400 FS 1047 1 0.6300 0.0000
DefRow: ROW_175 core 257.0400 1111.4200 N 1047 1 0.6300 0.0000
DefRow: ROW_176 core 257.0400 1116.3000 FS 1047 1 0.6300 0.0000
DefRow: ROW_177 core 257.0400 1121.1800 N 1047 1 0.6300 0.0000
DefRow: ROW_178 core 257.0400 1126.0600 FS 1047 1 0.6300 0.0000
DefRow: ROW_179 core 257.0400 1130.9400 N 1047 1 0.6300 0.0000
DefRow: ROW_180 core 257.0400 1135.8200 FS 1047 1 0.6300 0.0000
DefRow: ROW_181 core 257.0400 1140.7000 N 1047 1 0.6300 0.0000
DefRow: ROW_182 core 257.0400 1145.5800 FS 1047 1 0.6300 0.0000
DefRow: ROW_183 core 257.0400 1150.4600 N 1047 1 0.6300 0.0000
DefRow: ROW_184 core 257.0400 1155.3400 FS 1047 1 0.6300 0.0000
DefRow: ROW_185 core 257.0400 1160.2200 N 1047 1 0.6300 0.0000
DefRow: ROW_186 core 257.0400 1165.1000 FS 1047 1 0.6300 0.0000
DefRow: ROW_187 core 257.0400 1169.9800 N 1047 1 0.6300 0.0000
DefRow: ROW_188 core 257.0400 1174.8600 FS 1047 1 0.6300 0.0000
DefRow: ROW_189 core 257.0400 1179.7400 N 1047 1 0.6300 0.0000
DefRow: ROW_190 core 257.0400 1184.6200 FS 1047 1 0.6300 0.0000
DefRow: ROW_191 core 257.0400 1189.5000 N 1047 1 0.6300 0.0000
DefRow: ROW_192 core 257.0400 1194.3800 FS 1047 1 0.6300 0.0000
DefRow: ROW_193 core 257.0400 1199.2600 N 1047 1 0.6300 0.0000
DefRow: ROW_194 core 257.0400 1204.1400 FS 1047 1 0.6300 0.0000
DefRow: ROW_195 core 257.0400 1209.0200 N 1047 1 0.6300 0.0000
DefRow: ROW_196 core 257.0400 1213.9000 FS 1047 1 0.6300 0.0000
DefRow: ROW_197 core 257.0400 1218.7800 N 1047 1 0.6300 0.0000
DefRow: ROW_198 core 257.0400 1223.6600 FS 1047 1 0.6300 0.0000
DefRow: ROW_199 core 257.0400 1228.5400 N 1047 1 0.6300 0.0000
DefRow: ROW_200 core 257.0400 1233.4200 FS 1047 1 0.6300 0.0000
DefRow: ROW_201 core 257.0400 1238.3000 N 1047 1 0.6300 0.0000
DefRow: ROW_202 core 257.0400 1243.1800 FS 1047 1 0.6300 0.0000
DefRow: ROW_203 core 257.0400 1248.0600 N 1047 1 0.6300 0.0000
DefRow: ROW_204 core 257.0400 1252.9400 FS 1047 1 0.6300 0.0000
DefRow: ROW_205 core 257.0400 1257.8200 N 1047 1 0.6300 0.0000
DefRow: ROW_206 core 257.0400 1262.7000 FS 1047 1 0.6300 0.0000
DefRow: ROW_207 core 257.0400 1267.5800 N 1047 1 0.6300 0.0000
DefRow: ROW_208 core 257.0400 1272.4600 FS 1047 1 0.6300 0.0000
DefRow: ROW_209 core 257.0400 1277.3400 N 1047 1 0.6300 0.0000
DefRow: ROW_210 core 257.0400 1282.2200 FS 1047 1 0.6300 0.0000
DefRow: ROW_211 core 257.0400 1287.1000 N 1047 1 0.6300 0.0000
DefRow: ROW_212 core 257.0400 1291.9800 FS 1047 1 0.6300 0.0000
DefRow: ROW_213 core 257.0400 1296.8600 N 1047 1 0.6300 0.0000
DefRow: ROW_214 core 257.0400 1301.7400 FS 1047 1 0.6300 0.0000
DefRow: ROW_215 core 257.0400 1306.6200 N 1047 1 0.6300 0.0000
DefRow: ROW_216 core 257.0400 1311.5000 FS 1047 1 0.6300 0.0000
DefRow: ROW_217 core 257.0400 1316.3800 N 1047 1 0.6300 0.0000
DefRow: ROW_218 core 257.0400 1321.2600 FS 1047 1 0.6300 0.0000
DefRow: ROW_219 core 257.0400 1326.1400 N 1047 1 0.6300 0.0000
DefRow: ROW_220 core 257.0400 1331.0200 FS 1047 1 0.6300 0.0000
DefRow: ROW_221 core 257.0400 1335.9000 N 1047 1 0.6300 0.0000
DefRow: ROW_222 core 257.0400 1340.7800 FS 1047 1 0.6300 0.0000
DefRow: ROW_223 core 257.0400 1345.6600 N 1047 1 0.6300 0.0000
DefRow: ROW_224 core 257.0400 1350.5400 FS 1047 1 0.6300 0.0000
DefRow: ROW_225 core 257.0400 1355.4200 N 1047 1 0.6300 0.0000
DefRow: ROW_226 core 257.0400 1360.3000 FS 1047 1 0.6300 0.0000
DefRow: ROW_227 core 257.0400 1365.1800 N 1047 1 0.6300 0.0000
DefRow: ROW_228 core 257.0400 1370.0600 FS 1047 1 0.6300 0.0000
DefRow: ROW_229 core 257.0400 1374.9400 N 1047 1 0.6300 0.0000
DefRow: ROW_230 core 257.0400 1379.8200 FS 1047 1 0.6300 0.0000
DefRow: ROW_231 core 257.0400 1384.7000 N 1047 1 0.6300 0.0000
DefRow: ROW_232 core 257.0400 1389.5800 FS 1047 1 0.6300 0.0000
DefRow: ROW_233 core 257.0400 1394.4600 N 1047 1 0.6300 0.0000
DefRow: ROW_234 core 257.0400 1399.3400 FS 1047 1 0.6300 0.0000
DefRow: ROW_235 core 257.0400 1404.2200 N 1047 1 0.6300 0.0000
DefRow: ROW_236 core 257.0400 1409.1000 FS 1047 1 0.6300 0.0000
DefRow: ROW_237 core 257.0400 1413.9800 N 1047 1 0.6300 0.0000
DefRow: ROW_238 core 257.0400 1418.8600 FS 1047 1 0.6300 0.0000
DefRow: ROW_239 core 257.0400 1423.7400 N 1047 1 0.6300 0.0000
DefRow: ROW_240 core 257.0400 1428.6200 FS 1047 1 0.6300 0.0000
DefRow: ROW_241 core 257.0400 1433.5000 N 1047 1 0.6300 0.0000
DefRow: ROW_242 core 257.0400 1438.3800 FS 1047 1 0.6300 0.0000
DefRow: ROW_243 core 257.0400 1443.2600 N 1047 1 0.6300 0.0000
DefRow: ROW_244 core 257.0400 1448.1400 FS 1047 1 0.6300 0.0000
DefRow: ROW_245 core 257.0400 1453.0200 N 1047 1 0.6300 0.0000
DefRow: ROW_246 core 257.0400 1457.9000 FS 1047 1 0.6300 0.0000
DefRow: ROW_247 core 257.0400 1462.7800 N 1047 1 0.6300 0.0000
DefRow: ROW_248 core 257.0400 1467.6600 FS 1047 1 0.6300 0.0000
DefRow: ROW_249 core 257.0400 1472.5400 N 1047 1 0.6300 0.0000
DefRow: ROW_250 core 257.0400 1477.4200 FS 1047 1 0.6300 0.0000
DefRow: ROW_251 core 257.0400 1482.3000 N 1047 1 0.6300 0.0000
DefRow: ROW_252 core 257.0400 1487.1800 FS 1047 1 0.6300 0.0000
DefRow: ROW_253 core 257.0400 1492.0600 N 1047 1 0.6300 0.0000
DefRow: ROW_254 core 257.0400 1496.9400 FS 1047 1 0.6300 0.0000
DefRow: ROW_255 core 257.0400 1501.8200 N 1047 1 0.6300 0.0000
DefRow: ROW_256 core 257.0400 1506.7000 FS 1047 1 0.6300 0.0000
DefRow: ROW_257 core 257.0400 1511.5800 N 1047 1 0.6300 0.0000
DefRow: ROW_258 core 257.0400 1516.4600 FS 1047 1 0.6300 0.0000
DefRow: ROW_259 core 257.0400 1521.3400 N 1047 1 0.6300 0.0000
DefRow: ROW_260 core 257.0400 1526.2200 FS 1047 1 0.6300 0.0000
DefRow: ROW_261 core 257.0400 1531.1000 N 1047 1 0.6300 0.0000
DefRow: ROW_262 core 257.0400 1535.9800 FS 1047 1 0.6300 0.0000
DefRow: ROW_263 core 257.0400 1540.8600 N 1047 1 0.6300 0.0000
DefRow: ROW_264 core 257.0400 1545.7400 FS 1047 1 0.6300 0.0000
DefRow: ROW_265 core 257.0400 1550.6200 N 1047 1 0.6300 0.0000
DefRow: ROW_266 core 257.0400 1555.5000 FS 1047 1 0.6300 0.0000
DefRow: ROW_267 core 257.0400 1560.3800 N 1047 1 0.6300 0.0000
DefRow: ROW_268 core 257.0400 1565.2600 FS 1047 1 0.6300 0.0000
DefRow: ROW_269 core 257.0400 1570.1400 N 1047 1 0.6300 0.0000
DefRow: ROW_270 core 257.0400 1575.0200 FS 1047 1 0.6300 0.0000
DefRow: ROW_271 core 257.0400 1579.9000 N 1047 1 0.6300 0.0000
DefRow: ROW_272 core 257.0400 1584.7800 FS 1047 1 0.6300 0.0000
DefRow: ROW_273 core 257.0400 1589.6600 N 1047 1 0.6300 0.0000
DefRow: ROW_274 core 257.0400 1594.5400 FS 1047 1 0.6300 0.0000
DefRow: ROW_275 core 257.0400 1599.4200 N 1047 1 0.6300 0.0000
DefRow: ROW_276 core 257.0400 1604.3000 FS 1047 1 0.6300 0.0000
DefRow: ROW_277 core 257.0400 1609.1800 N 1047 1 0.6300 0.0000
DefRow: ROW_278 core 257.0400 1614.0600 FS 1047 1 0.6300 0.0000
DefRow: ROW_279 core 257.0400 1618.9400 N 1047 1 0.6300 0.0000
DefRow: ROW_280 core 257.0400 1623.8200 FS 1047 1 0.6300 0.0000
DefRow: ROW_281 core 257.0400 1628.7000 N 1047 1 0.6300 0.0000
DefRow: ROW_282 core 257.0400 1633.5800 FS 1047 1 0.6300 0.0000
DefRow: ROW_283 core 257.0400 1638.4600 N 1047 1 0.6300 0.0000
DefRow: ROW_284 core 257.0400 1643.3400 FS 1047 1 0.6300 0.0000
DefRow: ROW_285 core 257.0400 1648.2200 N 1047 1 0.6300 0.0000
DefRow: ROW_286 core 257.0400 1653.1000 FS 1047 1 0.6300 0.0000
DefRow: ROW_287 core 257.0400 1657.9800 N 1047 1 0.6300 0.0000
DefRow: ROW_288 core 257.0400 1662.8600 FS 1047 1 0.6300 0.0000
DefRow: ROW_289 core 257.0400 1667.7400 N 1047 1 0.6300 0.0000
DefRow: ROW_290 core 257.0400 1672.6200 FS 1047 1 0.6300 0.0000
DefRow: ROW_291 core 257.0400 1677.5000 N 1047 1 0.6300 0.0000
DefRow: ROW_292 core 257.0400 1682.3800 FS 1047 1 0.6300 0.0000
DefRow: ROW_293 core 257.0400 1687.2600 N 1047 1 0.6300 0.0000
DefRow: ROW_294 core 257.0400 1692.1400 FS 1047 1 0.6300 0.0000
DefRow: ROW_295 core 257.0400 1697.0200 N 1047 1 0.6300 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: Y 0.6100 3216 0.6100 1 6
Track: X 1.5750 931 1.2600 1 6
Track: X 0.3150 1863 0.6300 1 5
Track: Y 0.6100 3216 0.6100 1 5
Track: Y 0.6100 3216 0.6100 1 4
Track: X 0.3150 1863 0.6300 1 4
Track: X 0.3150 1863 0.6300 1 3
Track: Y 0.6100 3216 0.6100 1 3
Track: Y 0.6100 3216 0.6100 1 2
Track: X 0.3150 1863 0.6300 1 2
Track: X 0.3150 1863 0.6300 1 1
Track: Y 0.6100 3216 0.6100 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 1172.1150 2 1.8850
GCellGrid: X 0.3150 187 6.3000
GCellGrid: X 0.0000 2 0.3150
GCellGrid: Y 1958.7100 2 3.2900
GCellGrid: Y 0.6100 322 6.1000
GCellGrid: Y 0.0000 2 0.6100

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: GND -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="z80_topzera" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3f orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .z80_topzera15073.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: PAD_corner_tr CORNERP 917.0000 1705.0000 NE R180 - 01
IO: IOPADS_INST/PAD_D2 BOC16P 851.5450 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_D1 BOC16P 786.0900 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_D0 BOC16P 720.6350 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_CLK ICP 655.1800 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_nBUSRQ ICP 589.7250 1705.0000 N R180 - 01
IO: PAD_VDD VDDPADP 524.2750 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_nRESET ICP 458.8200 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_nNMI ICP 393.3650 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_nINT ICP 327.9100 1705.0000 N R180 - 01
IO: IOPADS_INST/PAD_nWAIT ICP 262.4550 1705.0000 N R180 - 01
IO: PAD_DUMMY_2 BD8P 0.0000 1579.3300 W R270 - 01
IO: IOPADS_INST/PAD_nWR BD8P 0.0000 1453.6600 W R270 - 01
IO: IOPADS_INST/PAD_nRD BD8P 0.0000 1327.9950 W R270 - 01
IO: IOPADS_INST/PAD_nIORQ BD8P 0.0000 1202.3300 W R270 - 01
IO: IOPADS_INST/PAD_nMREQ BD8P 0.0000 1076.6650 W R270 - 01
IO: IOPADS_INST/PAD_nM1 BD8P 0.0000 951.0000 W R270 - 01
IO: IOPADS_INST/PAD_D7 BOC16P 0.0000 825.3350 W R270 - 01
IO: IOPADS_INST/PAD_D6 BOC16P 0.0000 699.6700 W R270 - 01
IO: IOPADS_INST/PAD_D5 BOC16P 0.0000 574.0050 W R270 - 01
IO: IOPADS_INST/PAD_D4 BOC16P 0.0000 448.3400 W R270 - 01
IO: IOPADS_INST/PAD_D3 BOC16P 0.0000 322.6700 W R270 - 01
IO: PAD_corner_tl CORNERP 0.0000 1705.0000 NW R270 - 01
IO: PAD_corner_bl CORNERP 0.0000 0.0000 SW R0 - 01
IO: IOPADS_INST/PAD_A5 BD8P 262.4550 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_A4 BD8P 327.9100 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_A3 BD8P 393.3650 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_A2 BD8P 458.8200 0.0000 S R0 - 01
IO: PAD_GND GNDOPADP 524.2750 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_A1 BD8P 589.7250 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_A0 BD8P 655.1800 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_nBUSACK BD8P 720.6350 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_nHALT BD8P 786.0900 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_nRFSH BD8P 851.5450 0.0000 S R0 - 01
IO: PAD_corner_br CORNERP 917.0000 0.0000 SE R90 - 01
IO: PAD_DUMMY_1 BD8P 917.0000 322.6700 E R90 - 01
IO: IOPADS_INST/PAD_A15 BD8P 917.0000 448.3400 E R90 - 01
IO: IOPADS_INST/PAD_A14 BD8P 917.0000 574.0050 E R90 - 01
IO: IOPADS_INST/PAD_A13 BD8P 917.0000 699.6700 E R90 - 01
IO: IOPADS_INST/PAD_A12 BD8P 917.0000 825.3350 E R90 - 01
IO: IOPADS_INST/PAD_A11 BD8P 917.0000 951.0000 E R90 - 01
IO: IOPADS_INST/PAD_A10 BD8P 917.0000 1076.6650 E R90 - 01
IO: IOPADS_INST/PAD_A9 BD8P 917.0000 1202.3300 E R90 - 01
IO: IOPADS_INST/PAD_A8 BD8P 917.0000 1327.9950 E R90 - 01
IO: IOPADS_INST/PAD_A7 BD8P 917.0000 1453.6600 E R90 - 01
IO: IOPADS_INST/PAD_A6 BD8P 917.0000 1579.3300 E R90 - 01

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="nM1" status="fixed" >
  </Pin>
  <Pin name="nMREQ" status="fixed" >
  </Pin>
  <Pin name="nIORQ" status="fixed" >
  </Pin>
  <Pin name="nRD" status="fixed" >
  </Pin>
  <Pin name="nWR" status="fixed" >
  </Pin>
  <Pin name="nRFSH" status="fixed" >
  </Pin>
  <Pin name="nHALT" status="fixed" >
  </Pin>
  <Pin name="nBUSACK" status="fixed" >
  </Pin>
  <Pin name="nWAIT" status="fixed" >
  </Pin>
  <Pin name="nINT" status="fixed" >
  </Pin>
  <Pin name="nNMI" status="fixed" >
  </Pin>
  <Pin name="nRESET" status="fixed" >
  </Pin>
  <Pin name="nBUSRQ" status="fixed" >
  </Pin>
  <Pin name="CLK" status="fixed" >
  </Pin>
  <Pin name="A[15]" status="fixed" >
  </Pin>
  <Pin name="A[14]" status="fixed" >
  </Pin>
  <Pin name="A[13]" status="fixed" >
  </Pin>
  <Pin name="A[12]" status="fixed" >
  </Pin>
  <Pin name="A[11]" status="fixed" >
  </Pin>
  <Pin name="A[10]" status="fixed" >
  </Pin>
  <Pin name="A[9]" status="fixed" >
  </Pin>
  <Pin name="A[8]" status="fixed" >
  </Pin>
  <Pin name="A[7]" status="fixed" >
  </Pin>
  <Pin name="A[6]" status="fixed" >
  </Pin>
  <Pin name="A[5]" status="fixed" >
  </Pin>
  <Pin name="A[4]" status="fixed" >
  </Pin>
  <Pin name="A[3]" status="fixed" >
  </Pin>
  <Pin name="A[2]" status="fixed" >
  </Pin>
  <Pin name="A[1]" status="fixed" >
  </Pin>
  <Pin name="A[0]" status="fixed" >
  </Pin>
  <Pin name="D[7]" status="fixed" >
  </Pin>
  <Pin name="D[6]" status="fixed" >
  </Pin>
  <Pin name="D[5]" status="fixed" >
  </Pin>
  <Pin name="D[4]" status="fixed" >
  </Pin>
  <Pin name="D[3]" status="fixed" >
  </Pin>
  <Pin name="D[2]" status="fixed" >
  </Pin>
  <Pin name="D[1]" status="fixed" >
  </Pin>
  <Pin name="D[0]" status="fixed" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="z80_topzera">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
